### ISSUE TITLE
v0.2 TODO LIST

### ISSUE THREAD

**Issue by spirali** [spirali/estee#7]
- [x] Fix export of traces to chart after multi-cpus tasks
- [x] .dax loader
- [x] Multiple outputs of tasks
- [x] Network utilization chart
- [x] Directory refactoring
